on:
  schedule:
    - cron: '*/3 * * * *'
  #push:

name: deploy-tweet-bot


jobs:
  deploy-tweet-bot:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@main
      - uses: r-lib/actions/setup-r@v2
      
      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-packages
          restore-keys: |
            ${{ runner.os }}-
            
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: Rscript -e 'install.packages(c("googledrive","rtweet","forcats"), dependencies = TRUE)'
        
      - name: Tweet MeMe
        env:
          TWEET_BOT: ${{ secrets.TWEET_BOT }}
          TWEET_BOT_CONSUMER_KEY: ${{ secrets.TWEET_BOT_CONSUMER_KEY }}
          TWEET_BOT_CONSUMER_KEY_SECRET: ${{ secrets.TWEET_BOT_CONSUMER_KEY_SECRET }}
          TWEET_BOT_ACCESS_TOKEN: ${{ secrets.TWEET_BOT_ACCESS_TOKEN }}
          TWEET_BOT_ACCESS_SECRET: ${{ secrets.TWEET_BOT_ACCESS_SECRET }}
          GOOGLE_AUTHENTICATION_CREDENTIALS: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS }}
          MEME_FOLDER_1: ${{ secrets.MEME_FOLDER_1 }}
          MEME_FOLDER_2: ${{ secrets.MEME_FOLDER_2 }}
        run: |
          source('R/TweetBot.R')
         
        shell: Rscript {0}
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "just tweeted.."
          git push main
        
